import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


// src/app/layout.tsx
// import { ReactNode } from 'react';
// import { ThemeProvider, createTheme } from '@mui/material/styles';
// import CssBaseline from '@mui/material/CssBaseline';
// import '../styles/globals.css';

// const theme = createTheme({
//   palette: {
//     primary: {
//       main: '#1976d2',
//     },
//   },
// });

// const RootLayout = ({ children }: { children: ReactNode }) => (
//   <html lang="en">
//     <body>
//       <ThemeProvider theme={theme}>
//         <CssBaseline />
//         {children}
//       </ThemeProvider>
//     </body>
//   </html>
// );

// export default RootLayout;

